# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Docs/gyro_tester_zedboard_code/gyro_tester.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
# IP: The module: 'design_2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Docs/gyro_tester_zedboard_code/gyro_tester.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Docs/gyro_tester_zedboard_code/gyro_tester.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0.xci
# IP: The module: 'design_2_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Docs/gyro_tester_zedboard_code/gyro_tester.srcs/sources_1/bd/design_2/ip/design_2_xbar_0/design_2_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
