set_property PACKAGE_PIN W12 [get_ports HSI_A0]
set_property PACKAGE_PIN V12 [get_ports HSI_A1]
set_property IOSTANDARD LVCMOS33 [get_ports HSI_A0]
set_property IOSTANDARD LVCMOS33 [get_ports HSI_A1]

set_property PACKAGE_PIN AA11 [get_ports HSICK]
set_property IOSTANDARD LVCMOS33 [get_ports HSICK]

set_property PACKAGE_PIN J20 [get_ports SYNC_CK]
set_property IOSTANDARD LVCMOS25 [get_ports SYNC_CK]

set_property PACKAGE_PIN AA8 [get_ports HSI_DAM]
set_property PACKAGE_PIN AA9 [get_ports HSI_DAP]
set_property PACKAGE_PIN Y10 [get_ports HSI_DBM]
set_property PACKAGE_PIN AB9 [get_ports HSI_DBP]

set_property IOSTANDARD LVCMOS33 [get_ports HSI_DBP]
set_property IOSTANDARD LVCMOS33 [get_ports HSI_DAM]
set_property IOSTANDARD LVCMOS33 [get_ports HSI_DBM]
set_property IOSTANDARD LVCMOS33 [get_ports HSI_DAP]

set_property PACKAGE_PIN AB11 [get_ports HSI_DC]
set_property IOSTANDARD LVCMOS33 [get_ports HSI_DC]

set_property PACKAGE_PIN T22 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property PACKAGE_PIN T21 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property PACKAGE_PIN U22 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property PACKAGE_PIN U14 [get_ports LED7]
set_property IOSTANDARD LVCMOS33 [get_ports LED7]

set_property IOSTANDARD LVDS_25 [get_ports MCK_P]
set_property IOSTANDARD LVDS_25 [get_ports MCK_N]
set_property PACKAGE_PIN M19 [get_ports MCK_P]


set_property PACKAGE_PIN V10 [get_ports SPI_CS]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS]
set_property PACKAGE_PIN V8 [get_ports SPI_MISO]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MISO]
set_property PACKAGE_PIN W8 [get_ports SPI_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI]
set_property PACKAGE_PIN V9 [get_ports SPI_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SCK]

set_property PACKAGE_PIN H17 [get_ports SW6]
set_property IOSTANDARD LVCMOS25 [get_ports SW6]
set_property PACKAGE_PIN M15 [get_ports SW7]
set_property IOSTANDARD LVCMOS25 [get_ports SW7]

set_property PACKAGE_PIN J21 [get_ports STARTB]
set_property IOSTANDARD LVCMOS25 [get_ports STARTB]
set_property PACKAGE_PIN J22 [get_ports EOWB]
set_property IOSTANDARD LVCMOS25 [get_ports EOWB]
set_property PACKAGE_PIN M17 [get_ports EOT]
set_property IOSTANDARD LVCMOS25 [get_ports EOT]
set_property PACKAGE_PIN M19 [get_ports SORT0]
set_property IOSTANDARD LVCMOS25 [get_ports SORT0]
set_property PACKAGE_PIN M21 [get_ports SORT1]
set_property IOSTANDARD LVCMOS25 [get_ports SORT1]
set_property PACKAGE_PIN M23 [get_ports SORT2]
set_property IOSTANDARD LVCMOS25 [get_ports SORT2]
set_property PACKAGE_PIN M25 [get_ports SORT3]
set_property IOSTANDARD LVCMOS25 [get_ports SORT3]
set_property PACKAGE_PIN M27 [get_ports SORT4]
set_property IOSTANDARD LVCMOS25 [get_ports SORT4]
set_property PACKAGE_PIN M31 [get_ports SORT5]
set_property IOSTANDARD LVCMOS25 [get_ports SORT5]
set_property PACKAGE_PIN M33 [get_ports SORT6]
set_property IOSTANDARD LVCMOS25 [get_ports SORT6]
set_property PACKAGE_PIN M35 [get_ports SORT7]
set_property IOSTANDARD LVCMOS25 [get_ports SORT7]